PREFIX essglobal: <https://w3id.solidarityeconomy.coop/essglobal/V2a/vocab/>

SELECT ?uri ?orgStructure
WHERE {
	?uri rdf:type essglobal:SSEInitiative .
	OPTIONAL { ?uri essglobal:organisationalStructure ?orgStructure . }
		FILTER (regex(?uri, "^__UID__$"))
}
