PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX essglobal: <https://w3id.solidarityeconomy.coop/essglobal/V2a/vocab/>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ospostcode: <http://data.ordnancesurvey.co.uk/id/postcodeunit/>
PREFIX rov: <http://www.w3.org/ns/regorg#>
PREFIX osspatialrelations: <http://data.ordnancesurvey.co.uk/ontology/spatialrelations/>
PREFIX : <https://w3id.solidarityeconomy.coop/dotcoop-sandbox/>

SELECT ?name ?uri ?lat ?lng ?www ?street ?locality ?region ?postcode ?country
WHERE {
	?uri rdf:type essglobal:SSEInitiative .
	?uri gr:name ?name .
	OPTIONAL { ?uri foaf:homepage ?www .  
  filter (bif:length(str(?www)) <= 1024) }
	OPTIONAL { ?uri owl:sameAs ?sameas . }
	?uri essglobal:hasAddress ?hasAddress .
	OPTIONAL { ?hasAddress vcard:street-address ?street . }
	OPTIONAL { ?hasAddress vcard:postal-code ?postcode . }
	OPTIONAL { ?hasAddress vcard:locality ?locality . }
	OPTIONAL { ?hasAddress vcard:region ?region . }
	OPTIONAL { ?hasAddress vcard:country-name ?country . }
	?hasAddress geo:lat ?lat.
	?hasAddress geo:long ?lng.
}
ORDER BY DESC(?country) DESC(UCASE(?name))